# frozen_string_literal: true

# Auto-generated by CI — do not edit manually.

class Herozion < Formula
  desc "Security audit and performance analysis CLI tool for developers"
  homepage "https://herozion.io"
  version "1.1.66"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Herozion/scanner-releases/releases/download/v1.1.66/herozion-macos-amd64"
      sha256 "27512fa9e77f23b1fbd2d08c3f1fa3953e6720e0ff88052e8f98e62a048c4481"
    else
      url "https://github.com/Herozion/scanner-releases/releases/download/v1.1.66/herozion-macos-arm64"
      sha256 "2f4481433caa937221cc5fe66350c529fd34fbdc0e9c2caa4f49c2a67662d53e"
    end
  end

  on_linux do
    url "https://github.com/Herozion/scanner-releases/releases/download/v1.1.66/herozion-linux-amd64"
    sha256 "7a6584ec95ea73d7561760f4599b6eb5f92fdee4749270b3c5ae47db46de150a"
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      bin.install "herozion-macos-amd64" => "herozion"
    elsif OS.mac?
      bin.install "herozion-macos-arm64" => "herozion"
    else
      bin.install "herozion-linux-amd64" => "herozion"
    end
  end

  test do
    assert_match version.to_s, shell_output("\#<built-in function bin>/herozion --version")
  end
end
