# frozen_string_literal: true

# Auto-generated by CI — do not edit manually.

class Herozion < Formula
  desc "Security audit and performance analysis CLI tool for developers"
  homepage "https://herozion.io"
  version "1.0.42"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Herozion/scanner-releases/releases/download/v1.0.42/herozion-macos-amd64"
      sha256 "f5f23c9610d36e5ee1e01d0bc8ad35a2a3c94dd39eb5723a4e7c16fd60e3ce38"
    else
      url "https://github.com/Herozion/scanner-releases/releases/download/v1.0.42/herozion-macos-arm64"
      sha256 "52ad0812922b5180abfe3c9106f9119dc977118b56e16fcdd7670a812ed3d721"
    end
  end

  on_linux do
    url "https://github.com/Herozion/scanner-releases/releases/download/v1.0.42/herozion-linux-amd64"
    sha256 "dbf1a3be7eca92a7511825fcc80147710b0ff2705f0b9d0513890119d1b2f089"
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      bin.install "herozion-macos-amd64" => "herozion"
    elsif OS.mac?
      bin.install "herozion-macos-arm64" => "herozion"
    else
      bin.install "herozion-linux-amd64" => "herozion"
    end
  end

  test do
    assert_match version.to_s, shell_output("\#<built-in function bin>/herozion --version")
  end
end
