# frozen_string_literal: true

# Auto-generated by CI — do not edit manually.

class Herozion < Formula
  desc "Security audit and performance analysis CLI tool for developers"
  homepage "https://herozion.io"
  version "1.2.24"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Herozion/scanner-releases/releases/download/v1.2.24/herozion-macos-amd64.tar.gz"
      sha256 "7d4a1424735f266b0f8098b728a67ee1559f9a53e0be2920b54afb8d4147c126"
    else
      url "https://github.com/Herozion/scanner-releases/releases/download/v1.2.24/herozion-macos-arm64.tar.gz"
      sha256 "1e73012bb269f6d42675d85677db9079262eff0238e8a2dbfd7ba32350699196"
    end
  end

  on_linux do
    url "https://github.com/Herozion/scanner-releases/releases/download/v1.2.24/herozion-linux-amd64"
    sha256 "e9309a6dc7e7252991d03bf262fdfa1518515731e4e5134fb083b4ea93f31857"
  end

  def install
    if OS.mac?
      # Homebrew auto-cd's into the tarball's single top-level directory during
      # stage, so paths here are relative to herozion-macos-{arch}/.
      arch_binary = Hardware::CPU.intel? ? "herozion-macos-amd64" : "herozion-macos-arm64"
      libexec.install Dir["*"]
      bin.install_symlink libexec/arch_binary => "herozion"
    else
      bin.install "herozion-linux-amd64" => "herozion"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herozion --version")
  end
end
